
package wellness.view;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michael
 */
public class CounselorPanel extends javax.swing.JPanel {

        private String selectedID = "";

    
    /**
     * Creates new form CPanel
     */
    public CounselorPanel() {
        initComponents();
                 // Attach selection listener to table
        tblManageC.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRow = tblManageC.getSelectedRow();
                if (selectedRow != -1) {
                    selectedID = tblManageC.getValueAt(selectedRow, 0).toString();
                    txtCName.setText(tblManageC.getValueAt(selectedRow, 1).toString());
                    txtCSpecialization.setText(tblManageC.getValueAt(selectedRow, 2).toString());
                    txtCAvailability.setText(tblManageC.getValueAt(selectedRow, 3).toString());
                }
            }
        });
    }
    
   
    
    // === GETTERS FOR CONTROLLER ===
    public JButton getAddButton() { return btnCAdd; }
    public JButton getUpdateButton() { return btnCUpdate; }
    public JButton getDeleteButton() { return btnCDelete; }
    public JButton getClearButton() { return btnCClearfields; }

    public String getSelectedID() { return selectedID; }

    public String getNameInput() { return txtCName.getText().trim(); }
    public String getSpecializationInput() { return txtCSpecialization.getText().trim(); }
    public Boolean getAvailabilityInput() { 
        String available = txtCAvailability.getText().trim();

            if (available.equalsIgnoreCase("Yes")) {
                return true;
            } else {
                return false;
            }
    }

    public DefaultTableModel getTableModel() {
        return (DefaultTableModel) tblManageC.getModel();
    }

    // === UTILITIES ===
    public void clearFields() {
        txtCName.setText("");
        txtCSpecialization.setText("");
        txtCAvailability.setText("");
        tblManageC.clearSelection();
        selectedID = "";
    }

    public void throwWarning(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.WARNING_MESSAGE);
    }

    public void throwSuccess(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlCounselors = new javax.swing.JPanel();
        lblCounselor = new javax.swing.JLabel();
        tabpnCounselors = new javax.swing.JTabbedPane();
        pnlManageCounselors = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblManageC = new javax.swing.JTable();
        lblCName = new javax.swing.JLabel();
        lblCSpecialization = new javax.swing.JLabel();
        lblCAvailability = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        txtCSpecialization = new javax.swing.JTextField();
        txtCAvailability = new javax.swing.JTextField();
        btnCAdd = new javax.swing.JButton();
        btnCUpdate = new javax.swing.JButton();
        btnCClearfields = new javax.swing.JButton();
        btnCDelete = new javax.swing.JButton();

        pnlCounselors.setName("pnlCounselors"); // NOI18N

        lblCounselor.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblCounselor.setText("Counselors:");
        lblCounselor.setName("lblCounselor"); // NOI18N

        tabpnCounselors.setName("tabpnCounselors"); // NOI18N

        pnlManageCounselors.setName("pnlManageCounselors"); // NOI18N

        jScrollPane2.setBorder(null);

        tblManageC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Specialization", "Availability"
            }
        ));
        jScrollPane2.setViewportView(tblManageC);

        lblCName.setText("Full Name: ");
        lblCName.setName("lblCName"); // NOI18N

        lblCSpecialization.setText("Specialization: ");
        lblCSpecialization.setName("lblCSpecialization"); // NOI18N

        lblCAvailability.setText("Availability: ");
        lblCAvailability.setName("lblCAvailability"); // NOI18N

        txtCName.setName("txtName"); // NOI18N

        txtCSpecialization.setName("txtCSpecialization"); // NOI18N

        txtCAvailability.setName("txtCAvailability"); // NOI18N

        btnCAdd.setText("Add Counselor");
        btnCAdd.setName("btnAddCounselor"); // NOI18N

        btnCUpdate.setText("Update Counselor");
        btnCUpdate.setName("btnUpdateCounselor"); // NOI18N

        btnCClearfields.setText("Clear Fields");
        btnCClearfields.setName("btnClearFields"); // NOI18N

        btnCDelete.setText("Delete Counselor");
        btnCDelete.setName("btnDeleteCounselor"); // NOI18N

        javax.swing.GroupLayout pnlManageCounselorsLayout = new javax.swing.GroupLayout(pnlManageCounselors);
        pnlManageCounselors.setLayout(pnlManageCounselorsLayout);
        pnlManageCounselorsLayout.setHorizontalGroup(
            pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageCounselorsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCName)
                    .addComponent(lblCSpecialization)
                    .addComponent(lblCAvailability)
                    .addComponent(btnCAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCSpecialization)
                    .addComponent(txtCAvailability)
                    .addGroup(pnlManageCounselorsLayout.createSequentialGroup()
                        .addGroup(pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCUpdate)
                            .addComponent(btnCClearfields, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        pnlManageCounselorsLayout.setVerticalGroup(
            pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageCounselorsLayout.createSequentialGroup()
                .addGroup(pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageCounselorsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCName)
                            .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCSpecialization)
                            .addComponent(txtCSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCAvailability)
                            .addComponent(txtCAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCAdd)
                            .addComponent(btnCUpdate))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManageCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCClearfields)
                            .addComponent(btnCDelete)))
                    .addGroup(pnlManageCounselorsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabpnCounselors.addTab("Manage Counselors", pnlManageCounselors);

        javax.swing.GroupLayout pnlCounselorsLayout = new javax.swing.GroupLayout(pnlCounselors);
        pnlCounselors.setLayout(pnlCounselorsLayout);
        pnlCounselorsLayout.setHorizontalGroup(
            pnlCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCounselorsLayout.createSequentialGroup()
                .addGroup(pnlCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCounselorsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabpnCounselors))
                    .addGroup(pnlCounselorsLayout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(lblCounselor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCounselorsLayout.setVerticalGroup(
            pnlCounselorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCounselorsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblCounselor)
                .addGap(18, 18, 18)
                .addComponent(tabpnCounselors, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCounselors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCounselors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCAdd;
    private javax.swing.JButton btnCClearfields;
    private javax.swing.JButton btnCDelete;
    private javax.swing.JButton btnCUpdate;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCAvailability;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblCSpecialization;
    private javax.swing.JLabel lblCounselor;
    private javax.swing.JPanel pnlCounselors;
    private javax.swing.JPanel pnlManageCounselors;
    private javax.swing.JTabbedPane tabpnCounselors;
    private javax.swing.JTable tblManageC;
    private javax.swing.JTextField txtCAvailability;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCSpecialization;
    // End of variables declaration                   
}
