/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wellness.view;

import javax.swing.event.ChangeEvent;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import wellness.controller.FeedbackController;
/**
 *
 * @author Koekie
 */
public class FeedbackPanel extends javax.swing.JPanel {

    /**
     * Creates new form FeedbackView
     */
    
    
    public FeedbackPanel() {
        initComponents();
        
        //change listener to update label with the slider value
        sldrRating.addChangeListener((ChangeEvent e) -> {
            int value = sldrRating.getValue();
            lblRatingValue.setText(String.valueOf(value));
        });
    }
    
    private FeedbackController controller;
    public void setController(FeedbackController controller) {
    this.controller = controller;
}
    
    //clear fields
    public void clearSubmissionFields(){   
        txtStudentNumber.setText("");
        txtaComments.setText("");
        sldrRating.setValue(3);
    }   
    
    //  Getters to be used in controller
    public JButton getSubmitButton(){   
        return btnSubmitFeedback;

    }

    
    public String getStudentNumber(){
        return txtStudentNumber.getText();
    }
    
    public String getComment(){
        return txtaComments.getText();
    }
    
    public int getRating(){
        return sldrRating.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tabFeedback = new javax.swing.JTabbedPane();
        panSubmitFeedback = new javax.swing.JPanel();
        sldrRating = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaComments = new javax.swing.JTextArea();
        btnSubmitFeedback = new javax.swing.JButton();
        lblRating = new javax.swing.JLabel();
        lblComments = new javax.swing.JLabel();
        lblFeedback = new javax.swing.JLabel();
        lblRatingValue = new javax.swing.JLabel();
        lblStudentNumber = new javax.swing.JLabel();
        txtStudentNumber = new javax.swing.JTextField();
        tabFeedbackHistory = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Feedback:");

        sldrRating.setMaximum(5);
        sldrRating.setMinimum(1);
        sldrRating.setValue(3);

        txtaComments.setColumns(20);
        txtaComments.setRows(5);
        jScrollPane1.setViewportView(txtaComments);

        btnSubmitFeedback.setText("Submit Feedback");
        btnSubmitFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitFeedbackActionPerformed(evt);
            }
        });

        lblRating.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRating.setText("Rating:");

        lblComments.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComments.setText("Comments:");

        lblFeedback.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lblFeedback.setText("Submit your Feedback:");

        lblRatingValue.setText("3");

        lblStudentNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStudentNumber.setText("Student Number:");

        javax.swing.GroupLayout panSubmitFeedbackLayout = new javax.swing.GroupLayout(panSubmitFeedback);
        panSubmitFeedback.setLayout(panSubmitFeedbackLayout);
        panSubmitFeedbackLayout.setHorizontalGroup(
            panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSubmitFeedbackLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSubmitFeedbackLayout.createSequentialGroup()
                        .addGroup(panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComments, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRating, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStudentNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFeedback)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSubmitFeedbackLayout.createSequentialGroup()
                                .addComponent(sldrRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRatingValue))
                            .addComponent(jScrollPane1)
                            .addComponent(txtStudentNumber))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panSubmitFeedbackLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnSubmitFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addGap(287, 287, 287))))
        );
        panSubmitFeedbackLayout.setVerticalGroup(
            panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSubmitFeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFeedback)
                .addGap(30, 30, 30)
                .addGroup(panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentNumber)
                    .addComponent(txtStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSubmitFeedbackLayout.createSequentialGroup()
                        .addGroup(panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRating)
                            .addGroup(panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sldrRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRatingValue)))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panSubmitFeedbackLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblComments)))
                .addGap(18, 18, 18)
                .addComponent(btnSubmitFeedback)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        tabFeedback.addTab("Submit Feedback", panSubmitFeedback);

        jButton1.setText("Show all feedback");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "feedback ID", "Student ID", "Comment", "rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout tabFeedbackHistoryLayout = new javax.swing.GroupLayout(tabFeedbackHistory);
        tabFeedbackHistory.setLayout(tabFeedbackHistoryLayout);
        tabFeedbackHistoryLayout.setHorizontalGroup(
            tabFeedbackHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFeedbackHistoryLayout.createSequentialGroup()
                .addGroup(tabFeedbackHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabFeedbackHistoryLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton1))
                    .addGroup(tabFeedbackHistoryLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        tabFeedbackHistoryLayout.setVerticalGroup(
            tabFeedbackHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabFeedbackHistoryLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(90, 90, 90))
        );

        tabFeedback.addTab("Feedback History", tabFeedbackHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabFeedback)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tabFeedback)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitFeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitFeedbackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel mdl = (DefaultTableModel) jTable1.getModel(); 
    
    for(String[] row : controller.feedbackControlView())
    {
       mdl.addRow(row);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitFeedback;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblRatingValue;
    private javax.swing.JLabel lblStudentNumber;
    private javax.swing.JPanel panSubmitFeedback;
    private javax.swing.JSlider sldrRating;
    private javax.swing.JTabbedPane tabFeedback;
    private javax.swing.JPanel tabFeedbackHistory;
    private javax.swing.JTextField txtStudentNumber;
    private javax.swing.JTextArea txtaComments;
    // End of variables declaration//GEN-END:variables
}
