/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wellness.view;

/**
 *
 * @author Koekie
 */
public class FeedbackPanel extends javax.swing.JPanel {

    /**
     * Creates new form FeedbackView
     */
    public FeedbackPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tabFeedback = new javax.swing.JTabbedPane();
        panSubmitFeedback = new javax.swing.JPanel();
        tabFeedbackHistory = new javax.swing.JPanel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Feedback:");

        javax.swing.GroupLayout panSubmitFeedbackLayout = new javax.swing.GroupLayout(panSubmitFeedback);
        panSubmitFeedback.setLayout(panSubmitFeedbackLayout);
        panSubmitFeedbackLayout.setHorizontalGroup(
            panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panSubmitFeedbackLayout.setVerticalGroup(
            panSubmitFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        tabFeedback.addTab("Submit Feedback", panSubmitFeedback);

        javax.swing.GroupLayout tabFeedbackHistoryLayout = new javax.swing.GroupLayout(tabFeedbackHistory);
        tabFeedbackHistory.setLayout(tabFeedbackHistoryLayout);
        tabFeedbackHistoryLayout.setHorizontalGroup(
            tabFeedbackHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        tabFeedbackHistoryLayout.setVerticalGroup(
            tabFeedbackHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        tabFeedback.addTab("Feedback History", tabFeedbackHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabFeedback)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tabFeedback)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panSubmitFeedback;
    private javax.swing.JTabbedPane tabFeedback;
    private javax.swing.JPanel tabFeedbackHistory;
    // End of variables declaration//GEN-END:variables
}
